// Kho dữ liệu 100 câu trắc nghiệm phát âm Pinyin chuẩn (gồm cả âm tiết đơn & âm tiết ghép)
export const LARGE_QUIZ_DATABASE = [
  { sound: "bā", options: ["bā", "pā", "mā", "fā"], correct: 0 },
  { sound: "pó", options: ["bó", "pó", "mò", "fó"], correct: 1 },
  { sound: "mǐ", options: ["bǐ", "pǐ", "mǐ", "fǐ"], correct: 2 },
  { sound: "fù", options: ["bù", "pù", "mù", "fù"], correct: 3 },
  { sound: "dā", options: ["dā", "tā", "nā", "lā"], correct: 0 },
  { sound: "tè", options: ["dé", "tè", "nè", "lè"], correct: 1 },
  { sound: "nǐ", options: ["dǐ", "tǐ", "nǐ", "lǐ"], correct: 2 },
  { sound: "lù", options: ["dù", "tù", "nù", "lù"], correct: 3 },
  { sound: "gē", options: ["gē", "kē", "hē", "lē"], correct: 0 },
  { sound: "kǔ", options: ["gǔ", "kǔ", "hǔ", "lǔ"], correct: 1 },
  { sound: "hā", options: ["gā", "kā", "hā", "lā"], correct: 2 },
  { sound: "jī", options: ["jī", "qī", "xī", "zhī"], correct: 0 },
  { sound: "qù", options: ["jù", "qù", "xù", "chù"], correct: 1 },
  { sound: "xiā", options: ["jiā", "qiā", "xiā", "shā"], correct: 2 },
  { sound: "zǎo", options: ["zǎo", "cǎo", "sǎo", "zhǎo"], correct: 0 },
  { sound: "cù", options: ["zù", "cù", "sù", "chù"], correct: 1 },
  { sound: "sè", options: ["zè", "cè", "sè", "shè"], correct: 2 },
  { sound: "zhǎo", options: ["zǎo", "cǎo", "zhǎo", "chǎo"], correct: 2 },
  { sound: "chā", options: ["zā", "cā", "zhā", "chā"], correct: 3 },
  { sound: "shù", options: ["sù", "cù", "zù", "shù"], correct: 3 },
  { sound: "rè", options: ["lè", "nè", "shè", "rè"], correct: 3 },

  // Từ 2 âm tiết ghép & biến điệu
  { sound: "bàba", options: ["bàba", "pàpa", "màma", "fàfa"], correct: 0 },
  { sound: "nǐhǎo", options: ["líhǎo", "nǐhǎo", "nǐhǎo", "mǐhǎo"], correct: 1 },
  { sound: "lǎoshī", options: ["nǎoshī", "lǎoshī", "rǎoshī", "cǎoshī"], correct: 1 },
  { sound: "kāfèi", options: ["gāfèi", "kāfèi", "hāfèi", "pāfèi"], correct: 1 },
  { sound: "hénèi", options: ["génèi", "kénèi", "hénèi", "fénèi"], correct: 2 },
  { sound: "jīchǎng", options: ["jīchǎng", "qīchǎng", "xīchǎng", "zhīchǎng"], correct: 0 },
  { sound: "xīguā", options: ["jīguā", "qīguā", "xīguā", "shīguā"], correct: 2 },
  { sound: "zúqiú", options: ["zúqiú", "cúqiú", "súqiú", "zhúqiú"], correct: 0 },
  { sound: "cánjiā", options: ["zánjiā", "cánjiā", "sánjiā", "chánjiā"], correct: 1 },
  { sound: "zhòngguó", options: ["zòngguó", "còngguó", "zhòngguó", "chòngguó"], correct: 2 },
  { sound: "chūnjié", options: ["zūnjié", "cūnjié", "zhūnjié", "chūnjié"], correct: 3 },
  { sound: "shuǐguǒ", options: ["suǐguǒ", "cuǐguǒ", "zuǐguǒ", "shuǐguǒ"], correct: 3 },
  { sound: "rénmín", options: ["lénmín", "nénmín", "shénmín", "rénmín"], correct: 3 },

  // Các vần ghép khó an - ang, in - ing, en - eng
  { sound: "bān", options: ["bān", "bāng", "bēn", "bēng"], correct: 0 },
  { sound: "bāng", options: ["bān", "bāng", "bēn", "bēng"], correct: 1 },
  { sound: "lín", options: ["lín", "líng", "lún", "lóng"], correct: 0 },
  { sound: "líng", options: ["lín", "líng", "lún", "lóng"], correct: 1 },
  { sound: "gēn", options: ["gān", "gāng", "gēn", "gēng"], correct: 2 },
  { sound: "gēng", options: ["gān", "gāng", "gēn", "gēng"], correct: 3 },
  { sound: "jīn", options: ["jīn", "jīng", "jūn", "jī"], correct: 0 },
  { sound: "jīng", options: ["jīn", "jīng", "jūn", "jī"], correct: 1 },
  { sound: "xīn", options: ["xīn", "xīng", "xūn", "xī"], correct: 0 },
  { sound: "xīng", options: ["xīn", "xīng", "xūn", "xī"], correct: 1 },

  // Âm cuộn lưỡi er & vận mẫu u, ü
  { sound: "ér", options: ["ér", "ěr", "èr", "érzi"], correct: 0 },
  { sound: "lüè", options: ["lüè", "nüè", "jué", "xué"], correct: 0 },
  { sound: "xué", options: ["lüè", "nüè", "jué", "xué"], correct: 3 },
  { sound: "yuán", options: ["juān", "xuān", "yuán", "quān"], correct: 2 },
  { sound: "huā", options: ["huā", "kuā", "shuā", "guā"], correct: 0 },
  { sound: "kuài", options: ["huài", "kuài", "shuāi", "guài"], correct: 1 },
  { sound: "duì", options: ["tuì", "duì", "huí", "shuǐ"], correct: 1 },
  { sound: "chōng", options: ["zhōng", "chōng", "shōng", "rōng"], correct: 1 },
  { sound: "quān", options: ["juān", "xuān", "yuán", "quān"], correct: 3 },
  { sound: "wēng", options: ["wēng", "dēng", "tēng", "nēng"], correct: 0 },

  // Nhóm phụ âm bật hơi & không bật hơi
  { sound: "bāo", options: ["bāo", "pāo", "māo", "fāo"], correct: 0 },
  { sound: "pāo", options: ["bāo", "pāo", "māo", "fāo"], correct: 1 },
  { sound: "dōu", options: ["dōu", "tōu", "nōu", "lōu"], correct: 0 },
  { sound: "tōu", options: ["dōu", "tōu", "nōu", "lōu"], correct: 1 },
  { sound: "gān", options: ["gān", "kān", "hān", "lān"], correct: 0 },
  { sound: "kān", options: ["gān", "kān", "hān", "lān"], correct: 1 },
  { sound: "jiān", options: ["jiān", "qiān", "xiān", "zhān"], correct: 0 },
  { sound: "qiān", options: ["jiān", "qiān", "xiān", "zhān"], correct: 1 },
  { sound: "zān", options: ["zān", "cān", "sān", "zhān"], correct: 0 },
  { sound: "cān", options: ["zān", "cān", "sān", "zhān"], correct: 1 },
  { sound: "zhān", options: ["zān", "cān", "zhān", "chān"], correct: 2 },
  { sound: "chān", options: ["zān", "cān", "zhān", "chān"], correct: 3 },

  // Thanh điệu (4 thanh)
  { sound: "mā", options: ["mā", "má", "mǎ", "mà"], correct: 0 },
  { sound: "má", options: ["mā", "má", "mǎ", "mà"], correct: 1 },
  { sound: "mǎ", options: ["mā", "má", "mǎ", "mà"], correct: 2 },
  { sound: "mà", options: ["mā", "má", "mǎ", "mà"], correct: 3 },
  { sound: "bā", options: ["bā", "bá", "bǎ", "bà"], correct: 0 },
  { sound: "bá", options: ["bā", "bá", "bǎ", "bà"], correct: 1 },
  { sound: "bǎ", options: ["bā", "bá", "bǎ", "bà"], correct: 2 },
  { sound: "bà", options: ["bā", "bá", "bǎ", "bà"], correct: 3 },
  { sound: "jī", options: ["jī", "jí", "jǐ", "jì"], correct: 0 },
  { sound: "jí", options: ["jī", "jí", "jǐ", "jì"], correct: 1 },
  { sound: "jǐ", options: ["jī", "jí", "jǐ", "jì"], correct: 2 },
  { sound: "jì", options: ["jī", "jí", "jǐ", "jì"], correct: 3 },

  // Từ 2 âm tiết đa dạng
  { sound: "fúwù", options: ["fúwù", "fúyù", "fúwǔ", "fúyǔ"], correct: 0 },
  { sound: "mìshū", options: ["mìsū", "mìshū", "mìzhū", "mìchū"], correct: 1 },
  { sound: "dàtáng", options: ["tàtáng", "dàtáng", "nàtáng", "làtáng"], correct: 1 },
  { sound: "tútú", options: ["dútú", "tútú", "nútú", "lútú"], correct: 1 },
  { sound: "nǐhǎo", options: ["líhǎo", "nǐhǎo", "nǐhǎo", "mǐhǎo"], correct: 1 },
  { sound: "lúnchuán", options: ["núnchuán", "lúnchuán", "rúnchuán", "cúnchuán"], correct: 1 },
  { sound: "guójiā", options: ["kuójiā", "guójiā", "huójiā", "luójiā"], correct: 1 },
  { sound: "kělè", options: ["gělè", "kělè", "hělè", "lělè"], correct: 1 },
  { sound: "huǒguō", options: ["guǒguō", "kuǒguō", "huǒguō", "luǒguō"], correct: 2 },
  { sound: "jiéguǒ", options: ["jiéguǒ", "qiéguǒ", "xiéguǒ", "zhéguǒ"], correct: 0 },
  { sound: "qīn'ài", options: ["jīn'ài", "qīn'ài", "xīn'ài", "chīn'ài"], correct: 1 },
  { sound: "xuéxí", options: ["juéxí", "quéxí", "xuéxí", "shuéxí"], correct: 2 },
  { sound: "zìjǐ", options: ["zìjǐ", "cìjǐ", "sìjǐ", "zhìjǐ"], correct: 0 },
  { sound: "cóngqián", options: ["zóngqián", "cóngqián", "sóngqián", "chóngqián"], correct: 1 },
  { sound: "sānshí", options: ["zānshí", "cānshí", "sānshí", "shānshí"], correct: 2 },
  { sound: "chēzhàn", options: ["zēzhàn", "cēzhàn", "zhēzhàn", "chēzhàn"], correct: 3 },
  { sound: "rìběn", options: ["lìběn", "nìběn", "shìběn", "rìběn"], correct: 3 },
  { sound: "máobǐ", options: ["náobǐ", "láobǐ", "máobǐ", "páobǐ"], correct: 2 },
  { sound: "píngguǒ", options: ["bíngguǒ", "píngguǒ", "míngguǒ", "fíngguǒ"], correct: 1 },
  { sound: "báibǐ", options: ["báibǐ", "páibǐ", "máibǐ", "fáibǐ"], correct: 0 }
];
